# Generated by Django 5.2.8 on 2025-11-22 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=150)),
                ("isbn", models.CharField(db_index=True, max_length=13, unique=True)),
                ("paginas", models.PositiveIntegerField()),
                (
                    "stock",
                    models.PositiveIntegerField(
                        help_text="Cantidad de ejemplares disponibles",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("publicado_en", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["-id"],
            },
        ),
    ]
